theme: jekyll-theme-cayman
title: Fumagalli Lab at QM University of London
description: An interdisciplinary, inclusive and collaborative research group combining genomics and data science to address some of most pressing questions in evolutionary biology
