theme: jekyll-theme-cayman
title: Fumagalli Lab at Queen Mary University of London
description: An interdisciplinary research group combining genomics and data science to address some of most urging questions in evolutionary biology
